server:
  port: ${SERVER_PORT:8086}

spring:
  application:
    name: food-notification-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5437/food_notification_db}
    username: ${SPRING_DATASOURCE_USERNAME:notification_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:notification_secure_pass_2026}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: food-notification-service
      auto-offset-reset: earliest

notification:
  kafka:
    topics:
      payment-events: payment.events
      order-events: order.events
      delivery-events: delivery.events
  stream:
    timeout-ms: 1800000
    heartbeat-interval-ms: 30000

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
