server:
  port: 8086

spring:
  application:
    name: food-notification-service

  datasource:
    url: jdbc:postgresql://localhost:5437/food_notification_db
    username: notification_admin
    password: notification_secure_pass_2026
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
